services:
  db:
    image: postgres:12
    restart: always
    volumes:
      # replace VOLUME_NAME with your volume name
      - /mnt/VOLUME_NAME/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: squid-archive

  ingest:
    depends_on:
      - db
    restart: on-failure
    image: subsquid/substrate-ingest:firesquid
    command: [
      "-e", "ws://node:9944",
      "-c", "10",
       "--prom-port", "9090",
       "--out", "postgres://postgres:postgres@db:5432/squid-archive"
    ]
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    ports:
      - "9090:9090" # prometheus port

  gateway:
    depends_on:
      - db
    image: subsquid/substrate-gateway:firesquid
    environment:
      RUST_LOG: "substrate_gateway=info,actix_server=info"
    command: [
       "--database-url", "postgres://postgres:postgres@db:5432/squid-archive",
       "--database-max-connections", "3", # max number of concurrent database connections
    ]
    ports:
      - "8888:8000"

  # Explorer service is optional.
  # It provides rich GraphQL API for querying archived data.
  # Many developers find it very useful for exploration and debugging.
  explorer:
    image: subsquid/substrate-explorer:firesquid
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: "squid-archive"
      DB_USER: "postgres"
      DB_PASS: "postgres"
    ports:
      - "4444:3000"

  node:
    # Replace `snapshot-DATE` with latest release (like `snapshot-2022-apr-29`)
    image: ghcr.io/subspace/node:snapshot-DATE
    volumes:
      # replace VOLUME_NAME with your volume name
      - /mnt/VOLUME_NAME/node-data:/var/subspace:rw
    ports:
      - "0.0.0.0:9944:9944"
    restart: unless-stopped
    command: [
      # 
      "--chain", "gemini-2a",
      "--base-path", "/var/subspace",
      "--execution", "wasm",
      "--state-pruning", "archive",
      "--rpc-cors", "all",
      "--rpc-methods", "safe",
      "--unsafe-ws-external",
      # replace NODE_NAME with your node name
      "--name", "NODE_NAME"
    ]
    healthcheck:
      timeout: 5s
      # If node setup takes longer then expected, you want to increase `interval` and `retries` number.
      interval: 30s
      retries: 5

