apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rpc-node
spec:
  serviceName: "rpc-node-service"
  replicas: 1
  selector:
    matchLabels:
      app: rpc-node
  template:
    metadata:
      labels:
        app: rpc-node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/rpc
                operator: In
                values:
                - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - rpc-node
              topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "rpc-nodes"
        effect: "NoSchedule"
      containers:
      - name: rpc-node
        image: ghcr.io/${REPO_ORG}/node:${DOCKER_TAG}
        envFrom:
        - configMapRef:
            name: rpc-node-config
        ports:
        - containerPort: 9944
        - containerPort: 9615
        volumeMounts:
        - name: rpc-node-data
          mountPath: /var/subspace
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          tcpSocket:
            port: 9944
          initialDelaySeconds: 60
          periodSeconds: 60
        readinessProbe:
          tcpSocket:
            port: 9944
          initialDelaySeconds: 30
          periodSeconds: 30
        command: ["/bin/sh", "-c"]
        args:
          - |
            run \
            --chain $(NETWORK_NAME) \
            --base-path /var/subspace \
            --state-pruning archive \
            --blocks-pruning archive \
            --listen-on /ip4/0.0.0.0/tcp/30333 \
            --listen-on /ip6/::/tcp/30333 \
            --dsn-external-address /ip4/$(EXTERNAL_IP)/udp/30433/quic-v1 \
            --dsn-external-address /ip4/$(EXTERNAL_IP)/tcp/30433 \
            --dsn-external-address /ip6/$(EXTERNAL_IP_V6)/udp/30433/quic-v1 \
            --dsn-external-address /ip6/$(EXTERNAL_IP_V6)/tcp/30433 \
            --node-key $(NODE_KEY) \
            --in-peers 500 \
            --out-peers 250 \
            --rpc-max-connections 10000 \
            --rpc-cors all \
            --rpc-listen-on 0.0.0.0:9944 \
            --rpc-methods safe \
            --prometheus-listen-on 0.0.0.0:9615 \
            --reserved-nodes /dns/bootstrap-0.$(NETWORK_NAME).subspace.network/tcp/30333/p2p/$(BOOTSTRAP_0_PEER_ID) \
            --bootstrap-nodes /dns/bootstrap-0.$(NETWORK_NAME).subspace.network/tcp/30333/p2p/$(BOOTSTRAP_0_PEER_ID) \
            --reserved-nodes /dns/bootstrap-1.$(NETWORK_NAME).subspace.network/tcp/30333/p2p/$(BOOTSTRAP_1_PEER_ID) \
            --bootstrap-nodes /dns/bootstrap-1.$(NETWORK_NAME).subspace.network/tcp/30333/p2p/$(BOOTSTRAP_1_PEER_ID)
      volumes:
      - name: rpc-node-data
        persistentVolumeClaim:
          claimName: rpc-node-pvc
