apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rpc-node-pvc
  namespace: rpc-node
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-storageclass
  resources:
    requests:
      storage: 100Gi
