module "devnet" {
  source          = "../../network-primitives"
  path-to-scripts = "../../network-primitives/scripts"
  network-name    = "devnet"
  bootstrap-node-config = {
    droplet_size        = var.droplet-size
    deployment-version  = 11
    regions             = ["ams3"]
    nodes-per-region    = 1
    additional-node-ips = []
    docker-org          = "subspace"
    docker-tag          = "snapshot-2023-mar-08"
    reserved-only       = false
    prune               = false
    genesis-hash        = ""
    node-dsn-port       = "30433"
  }
  full-node-config = {
    droplet_size        = var.droplet-size
    deployment-version  = 11
    regions             = ["sfo3"]
    nodes-per-region    = 1
    additional-node-ips = []
    docker-org          = "subspace"
    docker-tag          = "snapshot-2023-mar-08"
    reserved-only       = false
    prune               = false
    node-dsn-port       = "30433"
  }
  rpc-node-config = {
    droplet_size        = var.droplet-size
    deployment-version  = 11
    regions             = ["fra1"]
    nodes-per-region    = 1
    additional-node-ips = []
    docker-org          = "subspace"
    docker-tag          = "snapshot-2023-mar-08"
    domain-prefix       = "rpc"
    reserved-only       = false
    prune               = false
    node-dsn-port       = "30433"
  }
  farmer-node-config = {
    droplet_size           = var.droplet-size
    deployment-version     = 14
    regions                = ["blr1"]
    nodes-per-region       = 1
    additional-node-ips    = []
    docker-org             = "subspace"
    docker-tag             = "snapshot-2023-mar-08"
    reserved-only          = false
    prune                  = false
    plot-size              = "10G"
    reward-address         = var.farmer-reward-address
    force-block-production = false
    node-dsn-port          = "30433"
  }
  cloudflare_api_token = var.cloudflare_api_token
  cloudflare_email     = var.cloudflare_email
  do_token             = var.do_token
  ssh_identity         = var.ssh_identity
  datadog_api_key      = var.datadog_api_key
}
