---
- name: Deploy SSH keys for 'ubuntu' on AWS users from GitHub
  hosts: all
  become: yes
  tasks:
    - name: Add authorized keys for 'ubuntu' user from GitHub
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('url', item) }}"
      loop:
        - {{github_keys}}

- name: Deploy SSH keys for 'root' users on Hetzner from GitHub
  hosts: "*hetzner*"
  become: yes
  tasks:
    - name: Add authorized keys for 'root' user on hetzner from GitHub
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('url', item) }}"
      loop:
        - {{github_keys}}

- name: Deploy SSH keys for 'ec2-user' users on macOS from GitHub
  hosts: "*macos*"
  become: yes
  tasks:
    - name: Add authorized keys for 'ec2-user' user on AWS from GitHub
      authorized_key:
        user: ec2-user
        state: present
        key: "{{ lookup('url', item) }}"
      loop:
        - {{github_keys}}

- name: Deploy SSH keys for 'Administrator' users on Windows from GitHub
  hosts: "*windows*"
  become: yes
  tasks:
    - name: Add authorized keys for 'Administrator' user on AWS from GitHub
      authorized_key:
        user: Administrator
        state: present
        key: "{{ lookup('url', item) }}"
      loop:
        - {{github_keys}}
