{{- if .Values.blockscout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockscout-stack.fullname" . }}-blockscout-svc
  labels:
    app: {{ .Release.Name }}-blockscout-svc
    {{- include "blockscout-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.blockscout.service.type }}
  ports:
    - port: {{ .Values.blockscout.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-blockscout
{{- end }}