{{- if .Values.stats.enabled }}
{{- if .Values.stats.files.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: stats-cm
  labels:
    {{- include "blockscout-stack.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.stats.files.list }}
  {{ $key }}: {{ toYaml $value | indent 2 }}
  {{- end }}
{{- end }}
{{- end }}
