apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader-role
  namespace: {{ .Values.namespace | quote }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: {{ .Values.namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "account-squid.serviceAccountName" . }}-pod-read
    namespace: {{ .Values.namespace | quote }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager-role
  namespace: {{ .Values.namespace | quote }}
rules:
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-role-binding
  namespace: {{ .Values.namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "account-squid.serviceAccountName" . }}-admin
    namespace: {{ .Values.namespace | quote }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployment-manager-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-viewer
  namespace: {{ .Values.namespace | quote }}
rules:
  - apiGroups: [""]
    resources:
      - services
      - ingress
      - nodes
      - pods
    verbs:
      - get
      - list
  - apiGroups: [apiextensions.k8s.io]
    resources:
      - customresourcedefinitions
    verbs:
      - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-viewer
  namespace: {{ .Values.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-viewer
subjects:
  - kind: ServiceAccount
    name: {{ include "account-squid.serviceAccountName" . }}
    namespace: {{ .Values.namespace | quote }}
    apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "account-squid.fullname" . }}-admin-role-binding
  namespace: {{ .Values.namespace | quote }}
subjects:
  - kind: User
    name: {{ .Values.administrator.email }}
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: {{ include "account-squid.fullname" . }}-admin
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: {{ include "account-squid.serviceAccountName" . }}-admin
    namespace: {{ .Values.namespace | quote }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-grantor-binding
  namespace: {{ .Values.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-grantor
subjects:
  - kind: User
    name: {{ .Values.administrator.email }}
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: {{ include "account-squid.fullname" . }}-admin
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: {{ include "account-squid.serviceAccountName" . }}-admin
    namespace: {{ .Values.namespace | quote }}
    apiGroup: rbac.authorization.k8s.io
