---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "account-squid.fullname" . }}-postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD:  {{ .Values.postgres.postgresPassword | b64enc}}
  POSTGRES_USER:  {{ .Values.postgres.postgresUser | b64enc}}
