apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namespace }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "archive-squid.fullname" . }}
data:
  POSTGRES_PORT: {{ .Values.postgres.postgresPort }}
  POSTGRES_DB: {{ .Values.postgres.postgresDatabase }}
  POSTGRES_HOST: {{ .Values.postgres.postgresHost }}
  DB_NAME: {{ .Values.postgres.postgresDatabase }}
  DB_HOST: {{ .Values.postgres.postgresHost }}
  DB_PORT: {{ .Values.postgres.postgresPort }}
  files:
  - ../config/archive-env-file
