apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "archive-squid.fullname" . }}-app
  namespace: {{ Release.Namespace}}
  labels:
    {{- include "archive-squid.labels" . | nindent 4 }}
    app.kubernetes.io/component: "archive"
    app.kubernetes.io/part-of: "squid-archive"
    app.kubernetes.io/arch: {{.Values.arch}}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "archive-squid.selectorLabels" . | nindent 6 }} # has to match .spec.template.metadata.labels
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "archive-squid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "archive-squid.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: nginx:latest
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - mountPath: "/etc/nginx/nginx.conf"
            name: archive-nginx-config
            subPath: nginx.conf
          - mountPath: "/etc/nginx/proxy.conf"
            name: archive-nginx-config
            subPath: proxy.conf
        ports:
          - name: nginx
            containerPort: 80
            protocol: TCP
        # livenessProbe:
        #     httpGet:
        #       path: /health
        #       port: 80
        #     initialDelaySeconds: 15
        #     periodSeconds: 15
        #     timeoutSeconds: 5
        #     successThreshold: 1
        #     failureThreshold: 3
        livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
        readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 6
            periodSeconds: 10

      - name: postgres
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: postgres:14
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: {{ include "archive-squid.fullname" . }}-data
          - mountPath: "/var/lib/postgresql/postgres.conf"
            name: {{ include "archive-squid.fullname" . }}-postgres-config
            subPath: postgres.conf
        ports:
          - name: db
            containerPort: 5432
            protocol: TCP
        resources:
        {{- toYaml .Values.resources | nindent 12 }}
        env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "archive-squid.fullname" . }}-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "archive-squid.fullname" . }}-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "archive-squid.fullname" . }}-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "archive-squid.fullname" . }}-postgres-secret
                  key: POSTGRES_PASSWORD
        livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
            successThreshold: 1
            timeoutSeconds: 5
        readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5

      - name: node
        image: "{{ .Values.image_node.repository }}:{{ .Values.image_api.tag | default .Chart.AppVersion }}"
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - mountPath: "/var/subspace"
            name: archive-data
        env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "archive-squid.fullname" . }}-migration-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "archive-squid.fullname" . }}-migration-secret
                  key: DB_PASS

      - name: ingest
        image: "{{ .Values.image_ingest.repository }}:{{ .Values.image_ingest.tag | default .Chart.AppVersion }}"
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: ingest
            containerPort: 3000
            protocol: TCP
        command:
              - -e ws://node:9944
              - -c 10
              - --prom-port 9090
              - --out postgres://postgres:postgres@db:5432/squid-archive
        resources:
        {{- toYaml .Values.resources | nindent 12 }}
        env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: DB_HONODE_TLS_REJECT_UNAUTHORIZEDST

      - name: explorer
        image: subsquid/substrate-explorer:firesquid
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: explorer
            containerPort: 3000
            protocol: TCP
        env:
            - name: DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: DB_TYPE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "archive-squid.fullname" . }}-migration-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "archive-squid.fullname" . }}-migration-secret
                  key: DB_PASS
        # livenessProbe:
        #     httpGet:
        #       path: /graphql
        #       port: 4350
        #     initialDelaySeconds: 5
        #     periodSeconds: 10
        #     timeoutSeconds: 5
        #     successThreshold: 1
        #     failureThreshold: 3
        livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 30
        readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 6
            periodSeconds: 30

      - name: datadog
        image: datadog/agent
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
        env:
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "archive-squid.fullname" . }}-datadog-secret
                  key: DD_API_KEY
            - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
            - name: DD_LOGS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: DD_LOGS_ENABLED
            - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
            - name: DD_CONTAINER_EXCLUDE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: DD_CONTAINER_EXCLUDE

      - name: pg-health-check
        image: ghcr.io/subspace/health-check:latest
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: pghealth
            containerPort: 8080
            protocol: TCP
        env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "archive-squid.fullname" . }}-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "archive-squid.fullname" . }}-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: HEALTH_CHECK PORT
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "archive-squid.fullname" . }}-health-auth-secret
                  key: HEALTH_AUTH_SECRET
        livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
        readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 6
            periodSeconds: 30

      - name: prom-health-check
        image: ghcr.io/subspace/health-check:latest
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: processorhealth
            containerPort: 7070
            protocol: TCP
        env:
            - name: PROMETHEUS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: PROCESSOR_HEALTH_HOST
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "explorer-squid.fullname" . }}-configmap
                  key: PROCESSOR_HEALTH_PORT
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "archive-squid.fullname" . }}-health-auth-secret
                  key: HEALTH_AUTH_SECRET
        livenessProbe:
            tcpSocket:
              port: 7070
            initialDelaySeconds: 5
            periodSeconds: 30
        readinessProbe:
            tcpSocket:
              port: 7070
            initialDelaySeconds: 6
            periodSeconds: 30

      volumes:
        - name: {{ include "archive-squid.fullname" . }}-data
          persistentVolumeClaim:
            claimName: {{ include "archive-squid.fullname" . }}-data-pvc
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
        - name: {{ include "archive-squid.fullname" . }}-proxy-config
          configMap:
            name: {{ include "archive-squid.fullname" . }}-proxy-configmap
        - name: {{ include "archive-squid.fullname" . }}-postgres-config
          configMap:
            name: {{ include "archive-squid.fullname" . }}-postgres-configmap

      nodeSelector:{{}}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
