apiVersion: v1
kind: Service
metadata:
  name: {{ include "archive-squid.fullname" . }}-loadbal-svc
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ include "archive-squid.fullname" . }}-app
    chart: {{ include "archive-squid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    name: {{ include "archive-squid.fullname" . }}-app
    app: {{ include "archive-squid.fullname" . }}-app
  type: {{ .Values.lb_service.type }}
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    {{- range .Values.lb_service.lb_ports }}
    - port: {{ .port }}
      name: {{ .name }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
