apiVersion: v1
kind: Service
metadata:
  name: {{ include "archive-squid.fullname" . }}-loadbal-svc
  namespace: {{ .Values.namespace}}
  labels:
    {{- include "archive-squid.labels" . | nindent 4 }}
    app.kubernetes.io/component: "archive"
    app.kubernetes.io/part-of: "squid-archive"
    app.kubernetes.io/arch: {{.Values.arch}}
    app: {{ include "archive-squid.fullname" . }}
    app: {{ include "archive-squid.fullname" . }}-app
spec:
  selector:
    name: {{ include "archive-squid.fullname" . }}-app
    app: {{ include "archive-squid.fullname" . }}-app
    type: {{ .Values.lb_service.type }}
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    {{- range .Values.lb_service.lb_ports }}
    - port: {{ .port }}
      name: {{ .name }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
