apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: {{ include "archive-squid.fullname" . }}-pvc
     namespace: {{ Release.Namespace}}
     labels:
       app: {{ include "archive-squid.fullname" . }}-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.persistence.size}}
