---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ include "archive-squid.fullname" . }}-postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD:  {{ .Values.postgres.postgresPassword | b64enc }}
  POSTGRES_USER:  {{ .Values.postgres.postgresUser | b64enc }}
  DB_USER: {{ .Values.postgres.postgresUser | b64enc }}
  DB_PASSWORD: {{ .Values.postgres.postgresPassword | b64enc }}
