{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "archive-squid.serviceAccountName" . }}-pod-read
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "archive-squid.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "archive-squid.serviceAccountName" . }}-admin
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "archive-squid.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "archive-squid.serviceAccountName" . }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "archive-squid.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acme-cert-manager
  namespace: {{ .Values.namespace | quote }}
