{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "archive-squid.serviceAccountName" . }}-pod-read
  namespace: default
  labels:
    {{- include "archive-squid.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "archive-squid.serviceAccountName" . }}-pod-read
  namespace: {{ Release.Namespace}}
  labels:
    {{- include "archive-squid.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "archive-squid.serviceAccountName" . }}
  namespace: {{ Release.Namespace}}
  labels:
    {{- include "archive-squid.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.serviceAccount.create -}}
kind: ServiceAccount
metadata:
  name: {{ include "archive-squid.serviceAccountName" . }}-admin
  namespace: {{ Release.Namespace}}
  labels:
    {{- include "archive-squid.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acme-cert-manager
  namespace: {{ Release.Namespace}}
