apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namespace }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "explorer-squid.fullname" . }}
data:
  POSTGRES_PORT: {{ .Values.postgres.postgresPort }}
  POSTGRES_DB: {{ .Values.postgres.postgresDatabase }}
  DB_HOST : {{ .Values.postgres.postgresHost }}
  DB_PORT : {{ .Values.postgres.postgresPort }}
  DB_NAME : {{ .Values.postgres.postgresDatabase }}
  files:
  - ../config/explorer-env-file
