apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "explorer-squid.fullname" . }}-pvc-snapshot
  namespace: {{ Release.Namespace}}
  labels:
    {{- include "explorer-squid.labels" . | nindent 4 }}
    app.kubernetes.io/component: "explorer"
    app.kubernetes.io/part-of: "squid-explorer"
    app.kubernetes.io/arch: {{.Values.arch}}
    app: {{ include "explorer-squid.fullname" . }}
    app: {{ include "explorer-squid.fullname" . }}-app
spec:
  dataSource:
    name: {{ include "explorer-squid.fullname" . }}-pvc
    kind: VolumeSnapshot
    apiGroup: volumesnapshot.external-storage.k8s.io/v1/volumesnapshots
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: linode-block-storage-retain
# storageClassName: ssd-gp3
