---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "explorer-squid.fullname" . }}-postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD:  {{ .Values.postgres.postgresPassword | b64enc}}
  POSTGRES_USER:  {{ .Values.postgres.postgresUser | b64enc}}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "explorer-squid.fullname" . }}-migration-secret
type: Opaque
data:
  DB_PASS: {{ .Values.migration.dbPass | b64enc}}
  DB_USER: {{ .Values.migration.dbUser | b64enc}}
