apiVersion: v1
kind: Service
metadata:
  name: {{ include "explorer-squid.fullname" . }}-svc
  namespace: {{ Release.Namespace}}
  labels:
    {{- include "explorer-squid.labels" . | nindent 4 }}
    app.kubernetes.io/component: "explorer"
    app.kubernetes.io/part-of: "squid-explorer"
    app.kubernetes.io/arch: {{.Values.arch}}
    name: {{ include "explorer-squid.fullname" . }}-app
    app: {{ include "explorer-squid.fullname" . }}-app

spec:
  selector:
    name: {{ include "explorer-squid.fullname" . }}-app
    app: {{ include "explorer-squid.fullname" . }}-app
    type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      name: {{ .name }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
