---
# Ansible Inventory File - hosts.yml

# Bootstrap Node Servers
bootstrap:
  hosts:
    bootstrap-0.devnet.subspace.network:
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/deployer.pem
    bootstrap-1.devnet.subspace.network:
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/deployer.pem

# RPC Node Servers
rpc:
  hosts:
    rpc-0.devnet.subspace.network:
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/deployer.pem
    rpc-1.devnet.subspace.network:
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/deployer.pem

# Domain Node Servers
domain:
  hosts:
    domain-3.devnet.subspace.network:
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/deployer.pem

# Full Node Servers
full:
  hosts:
    54.162.117.174:
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/deployer.pem

# Farmer Node Servers
farmer:
  hosts:
    192.168.1.31:
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/deployer.pem
