version: "3.7"

networks:
  traefik-proxy:
    external: true
  loki:

services:
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    labels:
      - traefik.enable=true
      - traefik.http.services.loki.loadbalancer.server.port=3100
      - traefik.http.routers.loki.rule=Host(`logging.subspace.network`)
      - traefik.http.routers.loki.tls.certresolver=le
      - traefik.http.routers.loki.entrypoints=websecure
      - traefik.docker.network=traefik-proxy
    volumes:
      - /root/loki/conf/loki/etc/loki-config.yaml:/etc/loki/loki-config.yaml:ro
    networks:
      - loki
      - traefik-proxy

  promtail:
    image: grafana/promtail:2.9.0
    command: -config.file=/etc/promtail/config.yml
    ports:
      - 127.0.0.1:3200:3100
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.rule=Host(`grafana.subspace.network`)
      - traefik.http.routers.grafana.tls.certresolver=le
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.docker.network=traefik-proxy
    networks:
      - loki
      - traefik-proxy

volumes:
  grafana-data:
  loki-data:
