global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']
  - job_name: 'vmalert'
    static_configs:
      - targets: ['vmalert:8880']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']

  - job_name: 'aws-rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics

    # Optional: Add labels to identify this specific RabbitMQ instance
    relabel_configs:
      - target_label: 'instance'
        replacement: 'aws-mq-production'
      - target_label: 'service'
        replacement: 'rabbitmq'
