apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archival-node-pvc
  namespace: farmer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-storageclass
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: farmer-node-pvc
  namespace: farmer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-storageclass
  resources:
    requests:
      storage: 50Gi
