version: "3.7"

services:
  polkadot:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/polkadot:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://polkadot.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  statemint:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/statemint:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://statemint.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  acala:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/acala:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://acala-polkadot.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  astar:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/astar:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://astar.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  clover:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/clover:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://clover.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  moonbeam:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/moonbeam:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://moonbeam.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  parallel:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/parallel:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://parallel.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  kusama:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/kusama:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://kusama.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  statemine:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/statemine:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://statemine.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  karura:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/karura:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://karura.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  bifrost:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/bifrost:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://bifrost-parachain.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  khala:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/khala:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://khala.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  shiden:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/shiden:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://shiden.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  moonriver:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/moonriver:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://moonriver.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  calamari:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/calamari:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://calamari.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  kilt-spiritnet:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/kilt-spiritnet:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://spiritnet.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  basilisk:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/basilisk:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://basilisk.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  altair:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/altair:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://altair.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  parallel-heiko:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/parallel-heiko:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://parallel-heiko.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  kintsugi-btc:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/kintsugi-btc:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://kintsugi.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  bit.country-pioneer:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/bit.country-pioneer:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://pioneer.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  genshiro:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/genshiro:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://node.genshiro.io
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  unique-quartz:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/unique-quartz:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://us-ws-quartz.unique.network
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  picasso:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/picasso:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://picasso-rpc.composable.finance
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  encointer:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/encointer:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://api.kusama.encointer.org
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  crust-shadow:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/crust-shadow:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://rpc-shadow.crust.network/
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  robonomics:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/robonomics:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://kusama.rpc.robonomics.network/
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  zeitgeist:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/zeitgeist:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://rpc-0.zeitgeist.pm
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  subsocial:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/subsocial:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://para.subsocial.network
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  sakura:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/sakura:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://rpc.sakura.clover.finance
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  integritee:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/integritee:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://kusama.api.integritee.network
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  crab:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/crab:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://crab-parachain-rpc.darwinia.network/
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  litmus:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/litmus:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://rpc.litmus-parachain.litentry.io
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  kico:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/kico:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://rpc.api.kico.dico.io
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  centrifuge:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/centrifuge:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://fullnode.parachain.centrifuge.io
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  efinity:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/efinity:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://rpc.efinity.io
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  hydra:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/hydra:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://rpc-01.hydradx.io
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  interlay:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/interlay:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://api.interlay.io/parachain
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  composable:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/composable:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://rpc.composable.finance
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  nodle:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/nodle:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://nodle-parachain.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  equilibrium:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/equilibrium:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://node.pol.equilibrium.io/
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  phala:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/polkadot-archives/phala:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://api.phala.network/ws
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  sora:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/sora:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://ws.parachain-collator-1.c1.sora2.soramitsu.co.jp
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  turing:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/turing:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://turing.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  mangata:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/mangata:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://mangata-x.api.onfinality.io/ws?apikey=${ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]

  mangata:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /mnt/polkadot_archive_volume/kusama-archives/mangata:/archive
    restart: unless-stopped
    environment:
      DEBUG: 1
      SOURCE_CHAIN_RPC: wss://mangata-x.api.onfinality.io/ws?apikey={ONFINALITY_API_KEY}
      TARGET_DIR: /archive
    entrypoint: ["node", "/dist/tools/continuous-fetch-blocks-to-archive.js"]
