version: "3.7"
services:
  bootstrap-node:
    image: subspacelabs/subspace-node
    volumes:
      - /path/to/bootstrap-node:/var/subspace:rw
    ports:
      - "0.0.0.0:30333:30333"
    restart: unless-stopped
    command: [
      "--chain", "testnet",
      "--base-path", "/var/subspace",
      "--wasm-execution", "compiled",
      "--execution", "wasm",
      "--pruning", "archive",
      "--telemetry-url", "wss://telemetry.polkadot.io/submit/ 1",
      "--node-key", "GENERATED_NODE_KEY_HERE",
      # Following 3 lines are for farmer connection
      "--rpc-cors", "all",
      "--rpc-methods", "Unsafe",
      "--ws-external",
      "--validator",
    ]

  public-rpc-node:
    image: subspacelabs/subspace-node
    volumes:
      - /path/to/public-rpc-node:/var/subspace:rw
    ports:
      - "127.0.0.1:9933:9933"
      - "127.0.0.1:9944:9944"
    restart: unless-stopped
    command: [
      "--chain", "testnet",
      "--base-path", "/var/subspace",
      "--wasm-execution", "compiled",
      "--execution", "wasm",
      "--pruning", "archive",
      "--telemetry-url", "wss://telemetry.polkadot.io/submit/ 1",
      "--bootnodes", "/dns/bootstrap-node/tcp/30333/p2p/GENERATED_BOOTSTRAP_NODE_ID_HERE",
      "--rpc-cors", "all",
      "--rpc-external",
      "--ws-external",
    ]

  farmer:
    image: subspacelabs/subspace-farmer
    volumes:
      - /path/to/farmer-data:/var/subspace:rw
    restart: unless-stopped
    command: [
      "farm",
      "--ws-server", "ws://bootstrap-node:9944",
    ]
