version: "3.7"
services:
  bootstrap-node:
    image: ghcr.io/autonomys/node:snapshot-DATE
    volumes:
      - /path/to/bootstrap-node:/var/subspace:rw
    ports:
      - "0.0.0.0:30333:30333"
    restart: unless-stopped
    command: [
      "--chain", "testnet",
      "--base-path", "/var/subspace",
      "--execution", "wasm",
      "--pruning", "archive",
      "--pool-kbytes", "51200",
      "--node-key", "GENERATED_NODE_KEY_HERE",
      # Following 3 lines are for farmer connection
      "--rpc-cors", "all",
      "--rpc-methods", "safe",
      "--ws-external",
      "--validator",
    ]

  public-rpc-node:
    image: ghcr.io/autonomys/node:snapshot-DATE
    volumes:
      - /path/to/public-rpc-node:/var/subspace:rw
    ports:
      - "127.0.0.1:9933:9933"
      - "127.0.0.1:9944:9944"
    restart: unless-stopped
    command: [
      "--chain", "testnet",
      "--base-path", "/var/subspace",
      "--execution", "wasm",
      "--pruning", "archive",
      "--pool-kbytes", "51200",
      "--bootnodes", "/dns/bootstrap-node/tcp/30333/p2p/GENERATED_BOOTSTRAP_NODE_ID_HERE",
      "--rpc-cors", "all",
      "--rpc-external",
      "--ws-external",
      "--ws-max-connections", "10000",
    ]

  farmer:
    image: ghcr.io/autonomys/farmer:snapshot-DATE
    ports:
      - "127.0.0.1:9955:9955"
    volumes:
      - /path/to/farmer-data:/var/subspace:rw
    restart: unless-stopped
    command: [
      "farm",
      "--custom-path", "/var/subspace",
      "--node-rpc-url", "ws://bootstrap-node:9944",
      "--ws-server-listen-addr", "0.0.0.0:9955",
      # Sudo account on testnet
      "--reward-address", "5CXTmJEusve5ixyJufqHThmy4qUrrm6FyLCR7QfE4bbyMTNC",
      "--plot-size", "1000G",
    ]
