version: "3.7"
services:
  relayer:
    image: ghcr.io/autonomys/relayer:latest
    volumes:
      - /path/to/config:/config:ro
      - /path/to/archives:/archives:ro
    restart: unless-stopped
    environment:
      CHAIN_CONFIG_PATH: /config/config.json
