---
- name: Create Loki user
  user:
    name: loki
    comment: 'Loki user'
    shell: /usr/sbin/nologin
    state: present

- name: Creates Loki directory
  file:
    path: '/etc/loki'
    state: directory
    owner: loki
    group: loki
    recurse: true
    mode: 0755
  changed_when: false

- name: install unzip
  apt:
    name: unzip
    state: present

- name: download Loki
  get_url:
    url: 'https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki-linux-amd64.zip'
    dest: '/tmp/loki-linux-amd64.zip'
    mode: '0700'

- name: unarchive Loki
  unarchive:
    src: '/tmp/loki-linux-amd64.zip'
    remote_src: yes
    dest: '/tmp'

- name: Copy binary file
  copy:
    src: '/tmp/loki-linux-amd64'
    dest: '/usr/local/bin/loki'
    remote_src: true
    owner: loki
    group: loki
    mode: 755

- name: Copy loki config
  copy:
    src: 'loki.yml'
    dest: '/etc/loki/loki.yml'
    owner: loki
    group: loki

- name: Copy loki service file
  copy:
    src: 'loki.service'
    dest: '/etc/systemd/system/loki.service'
    owner: root
    group: root
    mode: 600

- name: start loki service
  systemd:
    name: loki
    state: restarted
    daemon_reload: true
    enabled: true
  changed_when: false
