module "gemini-3d" {
  source          = "../../network-primitives"
  path-to-scripts = "../../network-primitives/scripts"
  network-name    = "gemini-3d"
  bootstrap-node-config = {
    droplet_size        = var.droplet-size
    deployment-version  = 9
    regions             = []
    nodes-per-region    = 0
    additional-node-ips = var.hetzner_bootstrap_node_ips
    docker-org          = "subspace"
    docker-tag          = "gemini-3d-2023-may-15"
    reserved-only       = false
    prune               = false
    genesis-hash        = "0x7f489750cfe91e17fc19b42a5acaba41d1975cedd3440075d4a4b4171ad0ac20"
    dsn-listen-port     = 50001
    node-dsn-port       = 30434
  }
  full-node-config = {
    droplet_size        = var.droplet-size
    deployment-version  = 6
    regions             = []
    nodes-per-region    = 0
    additional-node-ips = var.hetzner_full_node_ips
    docker-org          = "subspace"
    docker-tag          = "gemini-3d-2023-may-15"
    reserved-only       = false
    prune               = false
    node-dsn-port       = 30434
  }
  rpc-node-config = {
    droplet_size        = var.droplet-size
    deployment-version  = 6
    regions             = []
    nodes-per-region    = 0
    additional-node-ips = var.hetzner_rpc_node_ips
    docker-org          = "subspace"
    docker-tag          = "gemini-3d-2023-may-15"
    domain-prefix       = "eu"
    reserved-only       = false
    prune               = false
    node-dsn-port       = 30434
    enable-domains      = false
    domain-id           = var.domain_id
  }
  farmer-node-config = {
    droplet_size           = var.droplet-size
    deployment-version     = 2
    regions                = []
    nodes-per-region       = 1
    additional-node-ips    = []
    docker-org             = "subspace"
    docker-tag             = "gemini-3d-2023-may-15"
    reserved-only          = false
    plot-size              = "10G"
    reward-address         = var.farmer-reward-address
    force-block-production = true
    prune                  = false
    node-dsn-port          = 30434
  }
  piece_cache_size     = "50G"
  cloudflare_api_token = var.cloudflare_api_token
  cloudflare_email     = var.cloudflare_email
  do_token             = var.do_token
  ssh_identity         = var.ssh_identity
  datadog_api_key      = var.datadog_api_key
}
