version: "3"

services:
  db:
    image: postgres:14
    shm_size: 1gb
    volumes:
      # replace VOLUME_NAME with your volume name
      - /VOLUME_NAME/postgresql/data:/var/lib/postgresql/data
    environment:
      # provide DB name
      POSTGRES_DB:
      # provide DB password
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all

  pghero:
    image: ankane/pghero
    container_name: pghero
    environment:
      DATABASE_URL: postgres://postgres:squid@postgres-db:5432/squid
    ports:
      - "8080:8080" 

  run-migrations:
    image: ghcr.io/subspace/blockexplorer-processor:latest
    restart: on-failure:5
    environment:
      DB_HOST: "db"
      # provide DB name
      DB_NAME:
      # provide DB password
      DB_PASS:
    depends_on:
      - db
    command: "npm run db:migrate"

  processor:
    image: ghcr.io/subspace/blockexplorer-processor:latest
    restart: on-failure
    environment:
      # provide archive endpoint
      ARCHIVE_ENDPOINT: 
      # provide chain RPC endpoint
      CHAIN_RPC_ENDPOINT:
      DB_HOST: "db"
      # provide DB name
      DB_NAME:
      # provide DB password
      DB_PASS:
      BATCH_SIZE: 20
    depends_on:
      - db
      - run-migrations
    ports:
      - "3000:3000"

  graphql:
    image: ghcr.io/subspace/blockexplorer-api-server:latest
    depends_on:
      - db
      - run-migrations
      - processor
    environment:
      DB_HOST: "db"
      # provide DB name
      DB_NAME:
      # provide DB password
      DB_PASS:
    ports:
      - "4350:4000"
