---
- name: Create prometheus group
  group:
    name: prometheus
    state: present

- name: Update the /etc/hosts file
  copy:
    src: 'hosts'
    dest: '/etc/hosts'
    owner: root
    group: prometheus
    mode: '0644'
