apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: explorer-pvc
  namespace: explorer-network
spec:
  dataSource:
    name: explorer-archive-snapshot
    kind: VolumeSnapshot
    apiGroup: volumesnapshot.external-storage.k8s.io/v1/volumesnapshots
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: linode-block-storage-retain
# storageClassName: ssd-gp3
