apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - postgres-configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - pv.yaml
  - pvc.yaml
  - secret.yaml
