# apiVersion: v1
# kind: Pod
# metadata:
#   labels:
#     test: liveness
#   name: liveness-http
# spec:
#   containers:
#   - name: liveness
#     image: registry.k8s.io/liveness
#     args:
#     - /server
#     livenessProbe:
#       httpGet:
#         path: /healthz
#         port: 8080
#         httpHeaders:
#         - name: Custom-Header
#           value: Awesome
#       initialDelaySeconds: 3
#       periodSeconds: 3
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: goproxy
#   labels:
#     app: goproxy
# spec:
#   containers:
#   - name: goproxy
#     image: registry.k8s.io/goproxy:0.1
#     ports:
#     - containerPort: 8080
#     readinessProbe:
#       tcpSocket:
#         port: 8080
#       initialDelaySeconds: 5
#       periodSeconds: 10
#     livenessProbe:
#       tcpSocket:
#         port: 8080
#       initialDelaySeconds: 15
#       periodSeconds: 20
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   labels:
#     test: liveness
#   name: liveness-exec
# spec:
#   containers:
#   - name: liveness
#     image: registry.k8s.io/busybox
#     args:
#     - /bin/sh
#     - -c
#     - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
#     livenessProbe:
#       exec:
#         command:
#         - cat
#         - /tmp/healthy
#       initialDelaySeconds: 5
#       periodSeconds: 5