apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader-role
  namespace: explorer-network
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: explorer-network
subjects:
# Kubernetes service account
  - kind: ServiceAccount
    name: service-account-pod-read
    apiGroup: rbac.authorization.k8s.io 
  kind: Role
  name: pod-reader-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager-role
  namespace: explorer-network
rules:
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-manager-role-binding
  namespace: explorer-network
subjects:
# Kubernetes service account
  - kind: ServiceAccount
    name: serviceaccount-explorer-admin
    apiGroup: rbac.authorization.k8s.io 
  kind: Role
  name: deployment-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-viewer
  namespace: explorer-network
rules:          # Authorization rules for this role
  - apiGroups:  # 1st API group
      - ''      # An empty string designates the core API group.
    resources:
      - services
      - ingress
      - nodes
      - pods
    verbs:
      - get
      - list
  - apiGroups: # 2nd API group
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-viewer
  namespace: explorer-network
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-viewer
subjects:
  - kind: ServiceAccount
    name: serviceaccount-explorer
    apiGroup: rbac.authorization.k8s.io 
    namespace: explorer-network
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: explorer-admin
  namespace: explorer-network
subjects:
  - kind: User
    name: muhammad@subspace.network
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: explorer-admin
    apiGroup: rbac.authorization.k8s.io 
  - kind: ServiceAccount
    name: serviceaccount-explorer-admin
    apiGroup: rbac.authorization.k8s.io 
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-grantor-binding
  namespace: explorer-network
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-grantor
subjects:
- apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: muhammad@subspace.network
    apiGroup: rbac.authorization.k8s.io 
  - kind: Group
    name: explorer-admin
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: serviceaccount-explorer-admin
    apiGroup: rbac.authorization.k8s.io 
    namespace: explorer-network
