version: "3.7"

volumes:
  archival_node_data: {}
  vmagentdata: {}

networks:
  traefik-proxy:
    external: true

services:
  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:latest
    depends_on:
      - "archival-node"
    ports:
      - 8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--httpListenAddr=0.0.0.0:8429"
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://vmetrics.subspace.network:8428/api/v1/write"

  agent:
    container_name: newrelic-infra
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    network_mode: bridge
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      NRIA_LICENSE_KEY: "${NR_API_KEY}"
      NRIA_DISPLAY_NAME: "${NETWORK_NAME}-rpc-node-${NODE_ID}"
    restart: unless-stopped

  # traefik reverse proxy with automatic tls management using let encrypt
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      - --api=false
      - --api.dashboard=false
      - --providers.docker
      - --log.level=info
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.le.acme.email=alerts@subspace.network
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    networks:
      - traefik-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt

  archival-node:
    image: ghcr.io/${NODE_ORG}/node:${NODE_TAG}
    volumes:
      - archival_node_data:/var/subspace:rw
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.archival-node.loadbalancer.server.port=9944"
      - "traefik.http.routers.archival-node.rule=Host(`${DOMAIN_PREFIX}-${NODE_ID}.${NETWORK_NAME}.subspace.network`) && Path(`/ws`)"
      - "traefik.http.routers.archival-node.tls=true"
      - "traefik.http.routers.archival-node.tls.certresolver=le"
      - "traefik.http.routers.archival-node.entrypoints=websecure"
      - "traefik.http.routers.archival-node.middlewares=redirect-https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
    ports:
      - "9615:9615"
    networks:
      - traefik-proxy
    logging:
      driver: loki
      options:
        loki-url: "https://logging.subspace.network/loki/api/v1/push"
    command:
      [
        "--chain",
        "${NETWORK_NAME}",
        "--base-path",
        "/var/subspace",
        "--execution",
        "wasm",
        "--state-pruning",
        "archive",
        "--blocks-pruning",
        "archive",
        "--listen-addr",
        "/ip4/0.0.0.0/tcp/30333",
        "--dsn-external-address",
        "/ip4/${EXTERNAL_IP}/udp/30433/quic-v1",
        "--dsn-external-address",
        "/ip4/${EXTERNAL_IP}/tcp/30433",
        "--node-key",
        "${NODE_KEY}",
        "--rpc-cors",
        "all",
        "--rpc-external",
        "--in-peers",
        "500",
        "--out-peers",
        "250",
        "--in-peers-light",
        "500",
        "--rpc-max-connections",
        "10000",
        "--prometheus-port",
        "9615",
        "--prometheus-external",
        "--reserved-nodes",
        "${BOOTSTRAP_NODE_0}",
        "--bootnodes",
        "${BOOTSTRAP_NODE_0}",
        "--reserved-nodes",
        "${BOOTSTRAP_NODE_1}",
        "--bootnodes",
        "${BOOTSTRAP_NODE_1}",
        "--dsn-reserved-peers",
        "${DSN_BOOTSTRAP_NODE_0}",
        "--dsn-bootstrap-nodes",
        "${DSN_BOOTSTRAP_NODE_0}",
        "--dsn-reserved-peers",
        "${DSN_BOOTSTRAP_NODE_1}",
        "--dsn-bootstrap-nodes",
        "${DSN_BOOTSTRAP_NODE_1}",
      ]
