version: "3.7"

volumes:
  archival_node_data: {}
  farmer_data: {}
  vmagentdata: {}

services:
  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:latest
    depends_on:
      - "archival-node"
    ports:
      - 8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--httpListenAddr=0.0.0.0:8429"
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=https://vmetrics.subspace.network:8428/api/v1/write"
      - "--remoteWrite.basicAuth.username=${VM_USER}"
      - "--remoteWrite.basicAuth.password=${VM_PASS}"
      - "--remoteWrite.basicAuth.tlsSkipVerify=true"

  agent:
    container_name: newrelic-infra
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    network_mode: bridge
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      NRIA_LICENSE_KEY: "${NR_API_KEY}"
      NRIA_DISPLAY_NAME: "${NETWORK_NAME}-farmer-node-${NODE_ID}"
    restart: unless-stopped

  farmer:
    depends_on:
      archival-node:
        condition: service_healthy
    image: ghcr.io/${REPO_ORG}/farmer:${DOCKER_TAG}
    volumes:
      - /home/ubuntu/subspace/farmer_data:/var/subspace:rw
    restart: unless-stopped
    ports:
      - "30533:30533/tcp"
      - "9616:9616"
    logging:
      driver: loki
      options:
        loki-url: "https://logging.subspace.network/loki/api/v1/push"
    command: [
      "farm", "path=/var/subspace,size=${PLOT_SIZE}",
      "--node-rpc-url", "ws://archival-node:9944",
      "--external-address", "/ip4/${EXTERNAL_IP}/tcp/30533",
      "--external-address", "/ip6/${EXTERNAL_IP_V6}/tcp/30533",
      "--listen-on", "/ip4/0.0.0.0/tcp/30533",
      "--listen-on", "/ip6/::/tcp/30533",
      "--reward-address", "${REWARD_ADDRESS}",
      "--metrics-endpoint=0.0.0.0:9616",
      "--cache-percentage", "${CACHE_PERCENTAGE}",
      "--farming-thread-pool-size", "${THREAD_POOL_SIZE}",
    ]

  archival-node:
    image: ghcr.io/${REPO_ORG}/node:${DOCKER_TAG}
    volumes:
      - archival_node_data:/var/subspace:rw
    restart: unless-stopped
    ports:
      - "30333:30333/tcp"
      - "30433:30433/tcp"
      - "9615:9615"
    logging:
      driver: loki
      options:
        loki-url: "https://logging.subspace.network/loki/api/v1/push"
    command: [
      "run",
      "--chain", "${NETWORK_NAME}",
      "--base-path", "/var/subspace",
      "--state-pruning", "archive",
      "--blocks-pruning", "256",
      "--sync", "full",
#      "--pot-external-entropy", "${POT_EXTERNAL_ENTROPY}",
      "--listen-on", "/ip4/0.0.0.0/tcp/30333",
      "--listen-on", "/ip6/::/tcp/30333",
      "--dsn-external-address", "/ip4/${EXTERNAL_IP}/tcp/30433",
      "--dsn-external-address", "/ip6/${EXTERNAL_IP_V6}/tcp/30433",
      "--node-key", "${NODE_KEY}",
      "--farmer",
      "--timekeeper",
      "--rpc-cors", "all",
      "--rpc-listen-on", "0.0.0.0:9944",
      "--rpc-methods", "unsafe",
      "--prometheus-listen-on", "0.0.0.0:9615",
      "--bootstrap-node", "/dns/bootstrap-0.${NETWORK_NAME}.subspace.network/tcp/30333/p2p/${BOOTSTRAP_0_PEER_ID}",
      "--bootstrap-node", "/dns/bootstrap-1.${NETWORK_NAME}.subspace.network/tcp/30333/p2p/${BOOTSTRAP_1_PEER_ID}",
      "--dsn-bootstrap-nodes", "/dns/bootstrap-0.${NETWORK_NAME}.subspace.network/tcp/30533/p2p/${BOOTSTRAP_0_SUBSPACE_PEER_ID}",
      "--dsn-bootstrap-nodes", "/dns/bootstrap-1.${NETWORK_NAME}.subspace.network/tcp/30533/p2p/${BOOTSTRAP_1_SUBSPACE_PEER_ID}",
      "--force-synced",
      "--force-authoring",
    ]
