version: "3.7"

volumes:
  archival_node_data: {}
  vmagentdata: {}

services:
  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:v1.93.4
    depends_on:
      - "archival-node"
    ports:
      - 8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./prometheus-vmagent.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--httpListenAddr=0.0.0.0:8429"
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://vmetrics.subspace.network:8428/api/v1/write"
    restart: always

  agent:
    container_name: newrelic-infra
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    network_mode: bridge
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      NRIA_LICENSE_KEY: "${NR_API_KEY}"
      NRIA_DISPLAY_NAME: "${NETWORK_NAME}-full-node-${NODE_ID}"
    restart: unless-stopped

  archival-node:
    image: ghcr.io/${NODE_ORG}/node:${NODE_TAG}
    volumes:
      - archival_node_data:/var/subspace:rw
    restart: unless-stopped
    ports:
      - "30333:30333"
      - "30433:30433"
      - "9615:9615"
    logging:
      driver: loki
      options:
        loki-url: "https://logging.subspace.network/loki/api/v1/push"
    command:
      [
        "--chain",
        "${NETWORK_NAME}",
        "--base-path",
        "/var/subspace",
        "--execution",
        "wasm",
        "--state-pruning",
        "archive",
        "--blocks-pruning",
        "256",
        "--listen-addr",
        "/ip4/0.0.0.0/tcp/30333",
        "--dsn-external-address",
        "/ip4/${EXTERNAL_IP}/tcp/30433",
        "--node-key",
        "${NODE_KEY}",
        "--in-peers",
        "1000",
        "--out-peers",
        "1000",
        "--dsn-in-connections",
        "1000",
        "--dsn-out-connections",
        "1000",
        "--dsn-pending-in-connections",
        "1000",
        "--dsn-pending-out-connections",
        "1000",
        "--in-peers-light",
        "500",
        "--rpc-max-connections",
        "10000",
        "--prometheus-port",
        "9615",
        "--prometheus-external",
        "--reserved-nodes",
        "${BOOTSTRAP_NODE_0}",
        "--bootnodes",
        "${BOOTSTRAP_NODE_0}",
        "--reserved-nodes",
        "${BOOTSTRAP_NODE_1}",
        "--bootnodes",
        "${BOOTSTRAP_NODE_1}",
        "--dsn-reserved-peers",
        "${DSN_BOOTSTRAP_NODE_0}",
        "--dsn-bootstrap-nodes",
        "${DSN_BOOTSTRAP_NODE_0}",
        "--dsn-reserved-peers",
        "${DSN_BOOTSTRAP_NODE_1}",
        "--dsn-bootstrap-nodes",
        "${DSN_BOOTSTRAP_NODE_1}",
      ]
