---
  - hosts: all
    gather_facts: False

    tasks:
    - name: Install vector agent
      shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | bash -s -- -y

    - name: Install Loki stack
      shell: |
        mkdir -p $HOME/loki && cd $HOME/loki
        curl -O -L "https://github.com/grafana/loki/releases/download/v2.8.4/loki-linux-amd64.zip"
        unzip "loki-linux-amd64.zip"
        chmod a+x "loki-linux-amd64"
        curl -O -L "https://github.com/grafana/loki/releases/download/v2.8.4/promtail-linux-amd64.zip"
        unzip promtail-linux-amd64.zip
        chmod a+x "promtail-linux-amd64"
        curl -O -L "https://github.com/grafana/loki/releases/download/v2.8.4/logcli-linux-amd64.zip"
        unzip "logcli-linux-amd64.zip"
        chmod a+x "logcli-linux-amd64"
        wget https://raw.githubusercontent.com/grafana/loki/main/cmd/loki/loki-local-config.yaml
        wget https://raw.githubusercontent.com/grafana/loki/main/clients/cmd/promtail/promtail-local-config.yaml

        ./loki-linux-amd64 -config.file=loki-local-config.yaml

        cat << EOF
        server:
          http_listen_port: 9080
          grpc_listen_port: 0
        positions:
          filename: /var/lib/promtail/positions.yaml
        clients:
          - url: http://localhost:3100/loki/api/v1/push
          - url: http://<grafana-cloud>:3100/loki/api/v1/push
        scrape_configs:
        - job_name: system
          decompression:
            enabled: true
            initial_sleep: 10s
            format: gz
          static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/**.gz

          - job_name: syslog
            syslog:
              listen_address: 0.0.0.0:1514
              labels:
                job: "syslog"
            relabel_configs:
              - source_labels: ['__syslog_message_hostname']
                target_label: 'host'
          - job_name: journal
            journal:
              max_age: 12h
              labels:
                job: systemd-journal
            relabel_configs:
              - source_labels: ['__journal__systemd_unit']
                target_label: 'unit'

        storage_config:
          boltdb_shipper:
            active_index_directory: /loki/boltdb-shipper-active
            cache_location: /loki/boltdb-shipper-cache
            cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
            shared_store: s3
          aws:
            s3: s3://<access_key>:<uri-encoded-secret-access-key>@<region>
            bucketnames: <bucket1,bucket2>
        schema_config:
          configs:
            - from: 2020-07-01
              store: boltdb-shipper
              object_store: aws
              schema: v11
              index:
                prefix: index_
                period: 24h
        EOF
