apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archive-pvc
  namespace: archive-network
spec:
  dataSource:
    name: archive-archive-snapshot
    kind: VolumeSnapshot
    apiGroup: volumesnapshot.external-storage.k8s.io/v1/volumesnapshots
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: linode-block-storage-retain
