apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: archive-storageclass
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
