apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: archive-storageclass
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer
