---
# This is a restrictive policy that requires users to run as an
# unprivileged user, blocks possible escalations to root, and requires use of
# several security mechanisms.
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'
spec:
  allowedHostPaths:
    - pathPrefix: "/"
      readOnly: true  # only allow read-only mounts
    - pathPrefix: "/graphql"
      readOnly: true  # only allow read-only mounts
  privileged: false # Required to prevent escalations to root. 
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
      - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim' # Assume persistentVolumes set up by admin are safe
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot' # Require the container to run without root seLinux:
    rule: 'RunAsAny' # This assumes nodes are using AppArmor rather than SELinux
    supplementalGroups:
      rule: 'MustRunAs'
      ranges: # Forbid adding the root group.
        - min: 1
          max: 65535
    runAsGroup:
      rule: 'MustRunAs'
      ranges: # Forbid adding the root group.
        - min: 1
          max: 65535
    fsGroup:
      rule: 'MustRunAs'
      ranges: # Forbid adding the root group.
        - min: 1
          max: 65535
  readOnlyRootFilesystem: true
