# pv.yaml
# https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html
# uses efs csi driver and storage class
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: archive-data-pv
spec:
  capacity:
    storage: 150Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-073d77123471b2917
