---
- name: Create Ansible user
  user:
    name: ansible
    comment: 'Ansible user'
    shell: /bin/bash

- name: Add ansible authorized key
  authorized_key:
    user: ansible
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    exclusive: yes

- name: Allow sudo for ansible
  copy:
    content: 'ansible ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/ansible
    mode: '0600'

- name: Create administrator user
  user:
    name: '{{ deployment_user }}'
    comment: 'admin user'
    shell: /bin/bash

- name: Add administrator authorized key
  authorized_key:
    user: '{{ deployment_user }}'
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    exclusive: yes

- name: Allow sudo for administrator
  copy:
    content: '{{ deployment_user }} ALL=(ALL) NOPASSWD: ALL'
    dest: '/etc/sudoers.d/{{ deployment_user }}'
    mode: '0600'
