apiVersion: v1
kind: Service
metadata:
  name: rpc-node-service
spec:
  selector:
    app: rpc-node
  ports:
  - name: rpc
    protocol: TCP
    port: 9944
    targetPort: 9944
  - name: prometheus
    protocol: TCP
    port: 9615
    targetPort: 9615
  clusterIP: none
