---
- name: Deploy Docker Compose
  hosts: all
  become: true
  tasks:
    - name: Copy Docker Compose file to the target server
      copy:
        src: "../files/{{ docker_compose_file }}"
        dest: "{{ ansible_env.HOME }}/subspace/{{ docker_compose_file }}"
        mode: '0644'
    - name: Deploy with Docker Compose
      shell: "docker-compose -f {{ ansible_env.HOME }}/subspace/{{ docker_compose_file }} up -d"
