apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namespace }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "squid.fullname" . }}
data:
  POSTGRES_PORT: {{ .Values.postgres.postgresPort }}
  POSTGRES_DB: {{ .Values.postgres.postgresDatabase }}
  POSTGRES_HOST : {{ .Values.postgres.postgresHost }}
  files:
  - ../config/explorer-env-file
