apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "squid.fullname" . }}-pvc
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ include "squid.name" . }}
    chart: {{ include "squid.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
