apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-mem-resourcequota
  namespace: {{ .Values.namespace | quote }}
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 16Gi
