apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prod-letsencrypt
spec:
  acme:
    email: alerts@subspace.network
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: prod-letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: alerts@subspace.network
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging-letsencrypt
spec:
  acme:
    email: alerts@subspace.network
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: alerts@subspace.network
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
