version: "3.7"

volumes:
  archival_node_data: {}
  farmer_data: {}
services:
  farmer:
    depends_on:
      archival-node:
        condition: service_healthy
    build:
      context: .
      dockerfile: $HOME/subspace/subspace/Dockerfile-farmer
    image: ghcr.io/subspace/farmer:latest
    volumes:
      - farmer_data:/var/subspace:rw
    restart: unless-stopped
    ports:
      - "30533:30533/udp"
      - "30533:30533/tcp"
      - "9616:9616"
    logging:
      driver: loki
      options:
        loki-url: "https://logging.subspace.network/loki/api/v1/push"
    command:
      [
        "farm",
        "path=/var/subspace,size=${PLOT_SIZE}",
        "--node-rpc-url",
        "ws://archival-node:9944",
        "--external-address",
        "/ip4/${EXTERNAL_IP}/udp/30533/quic-v1",
        "--listen-on",
        "/ip4/0.0.0.0/udp/30533/quic-v1",
        "--external-address",
        "/ip4/${EXTERNAL_IP}/tcp/30533",
        "--listen-on",
        "/ip4/0.0.0.0/tcp/30533",
        "--reward-address",
        "${REWARD_ADDRESS}",
        "--metrics-endpoint=0.0.0.0:9616",
      ]

  archival-node:
    build:
      context: .
      dockerfile: $HOME/subspace/subspace/Dockerfile-node
    image: ghcr.io/subspace/node:latest
    volumes:
      - archival_node_data:/var/subspace:rw
    restart: unless-stopped
    ports:
      - "30333:30333/udp"
      - "30433:30433/udp"
      - "30333:30333/tcp"
      - "30433:30433/tcp"
    logging:
      driver: loki
      options:
        loki-url: "https://logging.subspace.network/loki/api/v1/push"
    command:
      [
        "--chain",
        "${NETWORK_NAME}",
        "--base-path",
        "/var/subspace",
        "--execution",
        "wasm",
        "--state-pruning",
        "archive",
        "--blocks-pruning",
        "256",
        "--listen-addr",
        "/ip4/0.0.0.0/tcp/30333",
        "--dsn-external-address",
        "/ip4/${EXTERNAL_IP}/udp/30433/quic-v1",
        "--dsn-external-address",
        "/ip4/${EXTERNAL_IP}/tcp/30433",
        "--node-key",
        "${NODE_KEY}",
        "--validator",
        "--timekeeper",
        "--rpc-cors",
        "all",
        "--rpc-external",
        "--rpc-methods",
        "unsafe",
        "--reserved-nodes",
        "${BOOTSTRAP_NODE_0}",
        "--bootnodes",
        "${BOOTSTRAP_NODE_0}",
        "--reserved-nodes",
        "${BOOTSTRAP_NODE_1}",
        "--bootnodes",
        "${BOOTSTRAP_NODE_1}",
        "--dsn-reserved-peers",
        "${DSN_BOOTSTRAP_NODE_0}",
        "--dsn-bootstrap-nodes",
        "${DSN_BOOTSTRAP_NODE_0}",
        "--dsn-reserved-peers",
        "${DSN_BOOTSTRAP_NODE_1}",
        "--dsn-bootstrap-nodes",
        "${DSN_BOOTSTRAP_NODE_1}",
        "--force-synced",
        "--force-authoring",
      ]
