version: "3.7"

volumes:
  caddy_data: {}
  archival_node_data: {}
  vmagentdata: {}

services:
  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:latest
    depends_on:
      - "archival-node"
    ports:
      - 8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--httpListenAddr=0.0.0.0:8429"
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://vmetrics.subspace.network:8428/api/v1/write"

  agent:
    container_name: newrelic-infra
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    network_mode: bridge
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      NRIA_LICENSE_KEY: "${NR_API_KEY}"
      NRIA_DISPLAY_NAME: "devnet-rpc-node-${NODE_ID}"
    restart: unless-stopped

  # caddy reverse proxy with automatic tls management using let encrypt
  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=subspace_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy_data:/data

  archival-node:
    image: ghcr.io/${NODE_ORG}/node:${NODE_TAG}
    volumes:
      - archival_node_data:/var/subspace:rw
    restart: unless-stopped
    labels:
      caddy_0: ${DOMAIN_PREFIX}-${NODE_ID}.${NETWORK_NAME}.subspace.network
      caddy_0.handle_path_0: /ws
      caddy_0.handle_path_0.reverse_proxy: "{{upstreams 9944}}"
    ports:
      - "9615:9615"
    logging:
      driver: loki
      options:
        loki-url: "https://logging.subspace.network/loki/api/v1/push"
    command: [
      "--chain", "${NETWORK_NAME}",
      "--base-path", "/var/subspace",
      "--execution", "wasm",
#      "--enable-subspace-block-relay",
      "--state-pruning", "archive",
      "--blocks-pruning", "archive",
      "--listen-addr", "/ip4/0.0.0.0/tcp/30333",
      "--timekeeper",
      "--dsn-external-address", "/ip4/3.86.228.101/tcp/30433",
      "--node-key", "${NODE_KEY}",
      "--rpc-cors", "all",
      "--rpc-external",
      "--in-peers", "500",
      "--out-peers", "250",
      "--in-peers-light", "500",
      "--rpc-max-connections", "10000",
      "--prometheus-port", "9615",
      "--prometheus-external",
      "--reserved-nodes", "/dns/bootstrap-0.devnet.subspace.network/tcp/30333/p2p/12D3KooWLdPnDksKX43hEgV4N9EeJzm6x8wPWkHCvRaFBZvj4GBg",
      "--bootnodes", "/dns/bootstrap-0.devnet.subspace.network/tcp/30333/p2p/12D3KooWLdPnDksKX43hEgV4N9EeJzm6x8wPWkHCvRaFBZvj4GBg",
      "--reserved-nodes", "/dns/bootstrap-1.devnet.subspace.network/tcp/30333/p2p/12D3KooWM4PT6vTWji9y9BmHc1dZKH7EE6nSfX1bZMUejFviJypz",
      "--bootnodes", "/dns/bootstrap-1.devnet.subspace.network/tcp/30333/p2p/12D3KooWM4PT6vTWji9y9BmHc1dZKH7EE6nSfX1bZMUejFviJypz",
      "--dsn-reserved-peers", "/dns/bootstrap-0.devnet.subspace.network/tcp/30533/p2p/12D3KooWJgLU8DmkXwBpQtHgSURFfJ4f2SyuNVBgVY96aDJsDWFK",
      "--dsn-bootstrap-nodes", "/dns/bootstrap-0.devnet.subspace.network/tcp/30533/p2p/12D3KooWJgLU8DmkXwBpQtHgSURFfJ4f2SyuNVBgVY96aDJsDWFK",
      "--dsn-reserved-peers", "/dns/bootstrap-1.devnet.subspace.network/tcp/30533/p2p/12D3KooWEaTUuF6H36UWu1WrxE3ccGVB8UXavQ2FF1xmJ8SNC38V",
      "--dsn-bootstrap-nodes", "/dns/bootstrap-1.devnet.subspace.network/tcp/30533/p2p/12D3KooWEaTUuF6H36UWu1WrxE3ccGVB8UXavQ2FF1xmJ8SNC38V",
    ]
