version: "3.7"

volumes:
  archival_node_data: {}

services:
  archival-node:
    image: ghcr.io/${NODE_ORG}/node:${NODE_TAG}
    volumes:
      - archival_node_data:/var/subspace:rw
    restart: unless-stopped
    ports:
      - "30333:30333"
      - "30433:30433"
      - "40333:40333"
      - "8944:8944"
      - "9615:9615"
    logging:
      driver: loki
      options:
        loki-url: "https://logging.subspace.network/loki/api/v1/push"
    command:
      [
        "--chain",
        "${NETWORK_NAME}",
        "--base-path",
        "/var/subspace",
        "--execution",
        "wasm",
        "--state-pruning",
        "archive",
        "--blocks-pruning",
        "archive",
        "--listen-addr",
        "/ip4/0.0.0.0/tcp/30333",
        "--dsn-external-address",
        "/ip4/${EXTERNAL_IP}/tcp/30433",
        "--node-key",
        "${NODE_KEY}",
        "--rpc-cors",
        "all",
        "--rpc-external",
        "--in-peers",
        "500",
        "--out-peers",
        "250",
        "--in-peers-light",
        "500",
        "--rpc-max-connections",
        "10000",
        "--prometheus-port",
        "9615",
        "--prometheus-external",
        "--reserved-nodes",
        "${BOOTSTRAP_NODE_0}",
        "--bootnodes",
        "${BOOTSTRAP_NODE_0}",
        "--reserved-nodes",
        "${BOOTSTRAP_NODE_1}",
        "--bootnodes",
        "${BOOTSTRAP_NODE_1}",
        "--dsn-reserved-peers",
        "${DSN_BOOTSTRAP_NODE_0}",
        "--dsn-bootstrap-nodes",
        "${DSN_BOOTSTRAP_NODE_0}",
        "--dsn-reserved-peers",
        "${DSN_BOOTSTRAP_NODE_1}",
        "--dsn-bootstrap-nodes",
        "${DSN_BOOTSTRAP_NODE_1}",
        "--",
        "--chain=${NETWORK_NAME}",
        "--state-pruning",
        "archive",
        "--blocks-pruning",
        "archive",
        "--domain-id=${DOMAIN_ID}",
        "--base-path",
        "/var/subspace/core_${DOMAIN_LABEL}_domain",
        "--listen-addr",
        "/ip4/0.0.0.0/tcp/40333",
        "--rpc-cors",
        "all",
        "--rpc-port",
        "8944",
        "--unsafe-rpc-external",
        "--relayer-id=${RELAYER_DOMAIN_ID}",
        "--reserved-nodes",
        "${BOOTSTRAP_NODE_EVM_0}",
        "--bootnodes",
        "${BOOTSTRAP_NODE_EVM_0}",
      ]
