name: Deploy Docker Compose
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment (e.g. devnet, gemini)"
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      - name: Deploy using Ansible
        working-directory: ./ansible/network
        run: |
          ansible-playbook -i inventories/${{ github.event.inputs.environment }}/hosts.yml playbooks/deploy-docker-compose.yml
