name: Main CD for Ephememeral Devnet Deployment

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "!main"
    paths:
      - "testing-framework/hetzner/network/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/terraform_template_ephemeral_deploy.yml
    with:
      project: testing-framework
      instance: hetzner
      resource: network
      tf_workspace_name: ephemeral-devnet-hetzner
      tf_version: 1.5.7
      tf_organization: subspace
    secrets:
      TRANSCRYPT: ${{ secrets.TRANSCRYPT }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
